-- require("neodev").setup({
--     library = { plugins = { "nvim-dap-ui" }, types = true },
-- })
--
--
--
-- require('dapui').setup()
--
--
--
-- local dap = require('dap')
-- dap.configurations.python = {
--     {
--         type = 'python';
--         request = 'launch';
--         name = "Launch file";
--         program = "${file}";
--         pythonPath = function()
--             return '/home/baka/.asdf/shims/python'
--         end;
--     },
-- }
