# Rotate video in 90 degree increments.
Alt+LEFT script-message Cycle_Video_Rotate "counter-clockwise"
Alt+RIGHT script-message Cycle_Video_Rotate "clockwise"



mbtn_mid    script-binding uosc/menu
p           script-binding uosc/items
c           script-binding uosc/chapters
tab         script-binding uosc/toggle-ui
