# vo=gpu-next
gpu-api=opengl
# gpu-api=vulkan # I'm getting seg fault with this one
hwdec=auto
# gpu-context=waylandvk

# loop=yes
loop-playlist=yes

save-position-on-quit=yes
# https://mpv.io/manual/master/#options-watch-later-options
watch-later-options=start

cache=yes
demuxer-max-bytes=512MiB

osd-bar=no
border=no
# osd-level=1
# osd-duration=2500
# osd-playing-msg=${path}
osd-status-msg='${path}\n${time-pos} / ${duration}${?percent-pos:　(${percent-pos}%)}${?frame-drop-count:${!frame-drop-count==0:　Dropped: ${frame-drop-count}}}\n${?chapter:Chapter: ${chapter}}'
# osd-msg1=${path}
# osd-msg2=${path}
# osd-msg3=${path}


[wallpaper]
fullscreen=yes
title=mpv-wallpaper
geometry=100%x100%
border=no
no-window-dragging
x11-name=mpv-wallpaper
hwdec=vaapi
aid=no
loop-file=yes
idle=no
