# vo=gpu-next
gpu-api=opengl
# gpu-api=vulkan # I'm getting seg fault with this one
# hwdec=auto
# gpu-context=waylandvk

# loop=yes
loop-playlist=yes
save-position-on-quit=yes
cache=yes
demuxer-max-bytes=512MiB

osd-bar=no
border=no
# osd-level=1
# osd-duration=2500
# osd-playing-msg=${path}
osd-status-msg='${path}\n${time-pos} / ${duration}${?percent-pos:　(${percent-pos}%)}${?frame-drop-count:${!frame-drop-count==0:　Dropped: ${frame-drop-count}}}\n${?chapter:Chapter: ${chapter}}'
# osd-msg1=${path}
# osd-msg2=${path}
# osd-msg3=${path}

