return {
	-- "simonwinther/cppman.nvim",
	-- version = "*",
	-- cmd = "CPPMan",
	-- lazy = true,
	-- dependencies = {
	-- 	"folke/snacks.nvim",
	-- },
	-- opts = {
	-- 	picker = {
	-- 		provider = "snacks",
	-- 	},
	-- },
	-- -- Buffer-local maps in C/C++ files only, so they don't show up in other
	-- -- filetypes. The require() calls load the plugin on first use.
	-- init = function()
	-- 	vim.api.nvim_create_autocmd("FileType", {
	-- 		pattern = { "cpp", "c" },
	-- 		callback = function(args)
	-- 			vim.keymap.set("n", "<leader>cu", function()
	-- 				require("cppman").open_for(vim.fn.expand("<cword>"))
	-- 			end, { buffer = args.buf, desc = "[C++] open under cursor" })
	--
	-- 			vim.keymap.set("n", "<leader>ck", function()
	-- 				require("cppman").search()
	-- 			end, { buffer = args.buf, desc = "[C++] keyword search" })
	-- 		end,
	-- 	})
	-- end,
}
